#!/usr/bin/env bash
# Double the number of webservers
sudo apt -y update
sudo apt -y install nginx
sudo sed -i '49 i\ \tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default
sudo service nginx restart