#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
var=1
for var in {1..100}; do
    if (( var % 3 == 0)) && (( var % 5 == 0)); then
        echo "FizzBuzz"
    elif (( var % 3 == 0)); then
        echo "Fizz"
    elif (( var % 5 == 0)); then
        echo "Buzz"
    else
        echo "$var"
    fi
done
