#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
var=1
while [ $var -le 10 ]; do
    if (( var == 4 )); then
        echo "bad luck"
    elif (( var == 8 )); then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    var=$(( var + 1 ))
done
