#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
cp /etc/hosts ~/host_new
sed -i s/127.0.0.1/127.0.0.2/ ~/host_new
echo "8.8.8.8 facebook.com" >> ~/host_new
cp -f ~/host_new /etc/hosts
